name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run:  sudo apt-get install -y libdbus-1-dev && cargo build --verbose
    - name: Run tests
      run:  sudo apt-get install -y libdbus-1-dev  && cargo test --verbose
